resource "aws_key_pair" "demo" {
  key_name   = "demo"
  public_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDIOMx6XPOCNjRKxbopGF++h/RGdpfH/bQGH+IyCLCSSSqv/4lIKZejFgbrvB6b8bUdFFsoNueItxw4/tC8NzkRkb8E4x+aU2zakruHRiQI/SCy8FtzMkr2WNYYRR4DN+4scBmJloCrevkPY/nE/m4Qf2nZnp3136otFMsmUNBmidRyp6JuPmXuc+kROR6WpUAoBE1E4qTOsBLGvPEyIdjCLJl7voVvPYzWYwyP4qYgZlZ+G8srcmWRRTudbGDJsZUY3k9JLWFLdhWdwkwn9NVSayof1RyTQkkz1PEo5m/k/NhToUmQOqUEUhUJ/W+2ahvI0KLUM09Nd85Mr4Lmeya3zyG8/rrLJL0GKhduAQPkLRcRNG6pWCvTJ8tOLjYZI7f9QlZE+WpNn12Id6ZMTRj+ayIOrup7BYAr7DAfjKlewirCJ/RAM3KfhirDBupvbnR45nW9bZKTcc8J0apTPnyRcoAgFNHhq3LduKYpML59mcmurvyChKT2D1qG/BKaP00= tejat@DESKTOP-IAOUN4Q"
}

# public_key=file (id_rsa.pub)